name: Python application test

on:
  push:
    branches: [ "main" ] # Or your default branch, e.g., "master"
  pull_request:
    branches: [ "main" ] # Or your default branch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify a Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with unittest
      run: |
        python -m unittest discover tests
